# Generated by Django 5.1 on 2024-10-07 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_freelancer_avatar_freelancer_avatar_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomToken',
        ),
    ]
