# Generated by Django 5.1 on 2024-10-14 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_company_name_alter_freelancer_lastname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freelancer',
            old_name='role',
            new_name='availability',
        ),
        migrations.RenameField(
            model_name='freelancer',
            old_name='interests',
            new_name='education',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='information',
        ),
        migrations.AddField(
            model_name='freelancer',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='github_profile',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='linkedin_profile',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='portfolio_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
