# Generated by Django 5.1 on 2024-10-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_role_freelancer_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
