# Generated by Django 5.1 on 2024-10-14 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_freelancer_profile_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='hourly_rate',
        ),
    ]
