# Generated by Django 5.1 on 2024-10-14 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_freelancer_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
