# Generated by Django 5.1 on 2024-10-15 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_company_profile_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='avatar',
        ),
        migrations.AddField(
            model_name='freelancer',
            name='freelancer_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='freelancers/'),
        ),
    ]
