# Generated by Django 5.1 on 2024-11-03 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_freelancer_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='profile_completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='profile_completed',
            field=models.BooleanField(default=True),
        ),
    ]
