# Generated by Django 5.1 on 2024-11-03 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_company_phone_alter_freelancer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_language',
            field=models.CharField(blank=True, choices=[('es', 'Español'), ('en', 'English'), ('fr', 'Français'), ('de', 'Deutsch'), ('pt', 'Português')], default='es', max_length=50),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='language',
            field=models.CharField(blank=True, choices=[('es', 'Español'), ('en', 'English'), ('fr', 'Français'), ('de', 'Deutsch'), ('pt', 'Português')], default='es', max_length=50),
        ),
    ]
