# Generated by Django 5.1 on 2024-11-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_company_company_language_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='company',
            name='lastname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
