# Generated by Django 5.1 on 2024-10-14 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='Frelancer',
            new_name='freelancer',
        ),
    ]
