# Generated by Django 5.1 on 2024-11-03 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0002_rename_frelancer_service_freelancer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='status',
        ),
        migrations.RemoveField(
            model_name='job',
            name='step_completed',
        ),
        migrations.RemoveField(
            model_name='service',
            name='status',
        ),
        migrations.RemoveField(
            model_name='service',
            name='step_completed',
        ),
    ]
