# Generated by Django 5.1 on 2024-11-04 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0003_remove_job_status_remove_job_step_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='nestedcategory_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='subcategory_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='category_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='nestedcategory_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='subcategory_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
