# Generated by Django 5.1 on 2024-11-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0006_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.AddField(
            model_name='service',
            name='basic_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='basic_delivery_time',
            field=models.PositiveIntegerField(blank=True, help_text='Tiempo de entrega en días', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='basic_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='basic_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='basic_revisions',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='premium_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='premium_delivery_time',
            field=models.PositiveIntegerField(blank=True, help_text='Tiempo de entrega en días', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='premium_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='premium_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='premium_revisions',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='standard_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='standard_delivery_time',
            field=models.PositiveIntegerField(blank=True, help_text='Tiempo de entrega en días', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='standard_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='standard_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='standard_revisions',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
