# Generated by Django 5.1 on 2024-11-12 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0010_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=20),
        ),
    ]
