# Generated by Django 5.1 on 2024-10-07 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freelancer',
            old_name='Freelancer_avatar',
            new_name='avatar',
        ),
        migrations.RenameField(
            model_name='freelancer',
            old_name='Freelancer_language',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='freelancer',
            old_name='Freelancer_location',
            new_name='location',
        ),
    ]
