# urls.py
from django.urls import path, include
from rest_framework import routers
from .views import (
    CategoryViewSet, 
    SubcategoryViewSet, 
    ServiceViewSet, 
    NestedCategoryViewSet, 
    JobViewSet, 
    search_items,
    services_by_subcategory,
    subcategories_by_category,
    jobs_by_subcategory,
    create_job,
    create_service,
    nestedcategories_by_subcategory,
    ReviewViewSet,
    create_review,
    get_service_reviews,
    get_job_reviews,
    update_review,
    delete_review,
    get_service_details,
    get_service_plans,
    get_service_stats,
    apply_to_job,
    get_job_applications,
    update_application_status,
    check_application_status,
    get_my_applications,
    get_application_details,
    create_service_order,
    process_payment,
    get_my_orders,
    get_my_sales,
    check_service_order,
    get_my_service_requests,
    get_received_service_requests,
    update_service_request_status,
    update_service_order_status,
)

router = routers.DefaultRouter()
router.register(r'categories', CategoryViewSet)
router.register(r'subcategories', SubcategoryViewSet)
router.register(r'nestedcategories', NestedCategoryViewSet)
router.register(r'services', ServiceViewSet)
router.register(r'jobs', JobViewSet)
router.register(r'reviews', ReviewViewSet)

urlpatterns = [
    path('api/v1/', include(router.urls)),
    path('api/v1/search/', search_items, name='search_items'),
    path('api/v1/all-subcategories/', subcategories_by_category, name='all-subcategories'),
    path('api/v1/services/subcategory/<int:subcategory_id>/', services_by_subcategory, name='services-by-subcategory'),
    path('api/v1/jobs/subcategory/<int:subcategory_id>/', jobs_by_subcategory, name='jobs-by-subcategory'),
    path('api/v1/subcategories/category/<int:category_id>/', subcategories_by_category, name='subcategories-by-category'),
    path('api/v1/create-job/', create_job, name='create-job'),
    path('api/v1/create-service/', create_service, name='create-service'),
    path('api/v1/nestedcategories/subcategory/<int:subcategory_id>/', 
         nestedcategories_by_subcategory, 
         name='nestedcategories-by-subcategory'),
    path('api/v1/create-review/', create_review, name='create-review'),
    path('api/v1/service-reviews/<int:service_id>/', get_service_reviews, name='service-reviews'),
    path('api/v1/job-reviews/<int:job_id>/', get_job_reviews, name='job-reviews'),
    path('api/v1/reviews/<int:review_id>/', update_review, name='update-review'),
    path('api/v1/reviews/<int:review_id>/delete/', delete_review, name='delete-review'),
    path('api/v1/services/<int:service_id>/details/', get_service_details, name='service-details'),
    path('api/v1/services/<int:service_id>/plans/', get_service_plans, name='service-plans'),
    path('api/v1/services/<int:service_id>/stats/', get_service_stats, name='service-stats'),
    path('api/v1/jobs/<int:job_id>/apply/', apply_to_job, name='apply-to-job'),
    path('api/v1/jobs/<int:job_id>/applications/', 
         get_job_applications, 
         name='job-applications'),
    path('api/v1/applications/<int:application_id>/', 
         update_application_status, 
         name='update-application'),
    path('api/v1/jobs/<int:job_id>/check-application/', 
         check_application_status, 
         name='check-application-status'),
    path('api/v1/applications/my-applications/', 
         get_my_applications, 
         name='my-applications'),
    path('api/v1/applications/<int:application_id>/details/', 
         get_application_details, 
         name='application-details'),
    path('api/v1/services/<int:service_id>/order/', 
         create_service_order, 
         name='create-service-order'),
    path('api/v1/orders/<int:order_id>/pay/', 
         process_payment, 
         name='process-payment'),
    path('api/v1/orders/my-orders/', 
         get_my_orders, 
         name='my-orders'),
    path('api/v1/orders/my-sales/', 
         get_my_sales, 
         name='my-sales'),
    path('api/v1/services/<int:service_id>/check-order/', 
         check_service_order, 
         name='check-service-order'),
    path('api/v1/service-requests/my-requests/', 
         get_my_service_requests, 
         name='my-service-requests'),
    path('api/v1/service-requests/received/', 
         get_received_service_requests, 
         name='received-service-requests'),
    path('api/v1/service-requests/<int:request_id>/status/', 
         update_service_request_status, 
         name='update-service-request-status'),
    path('api/v1/orders/<int:order_id>/status/', 
         update_service_order_status, 
         name='update-service-order-status'),
]
