# Generated by Django 5.1 on 2024-08-17 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0004_alter_service_location_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='NestedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subcategory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='nestedcategories', to='postings.subcategory')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='nestedcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='postings.nestedcategory'),
        ),
    ]
