# Generated by Django 5.1 on 2024-08-17 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0006_user_image_user_information_user_interests_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='aviliability',
            new_name='availability',
        ),
        migrations.AlterField(
            model_name='nestedcategory',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nestedcategories', to='postings.subcategory'),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('information', models.TextField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='companies/')),
                ('interests', models.ManyToManyField(blank=True, related_name='companies', to='postings.category')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('salary', models.FloatField()),
                ('availability', models.BooleanField(default=True)),
                ('location', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='jobs/')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='postings.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postings.company')),
                ('nestedcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='postings.nestedcategory')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='postings.subcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postings.user')),
            ],
        ),
    ]
