# Generated by Django 5.1 on 2024-08-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0008_remove_job_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/'),
        ),
    ]
