# Generated by Django 5.1 on 2024-08-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0010_user_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_language',
            field=models.CharField(blank=True, choices=[('es', 'Español'), ('en', 'English'), ('fr', 'Français'), ('de', 'Deutsch')], default='es', max_length=50),
        ),
    ]
