# Generated by Django 5.1 on 2024-08-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0011_user_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_language',
            field=models.CharField(blank=True, choices=[('Español', 'Español'), ('English', 'English'), ('Français', 'Français'), ('Deutsch', 'Deutsch')], default='es', max_length=50),
        ),
    ]
