# Generated by Django 5.1 on 2024-08-18 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0013_alter_user_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='compay_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='companies/'),
        ),
    ]
