# Generated by Django 5.1 on 2024-08-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0014_company_compay_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_language',
            field=models.CharField(blank=True, choices=[('es', 'Español'), ('en', 'English'), ('fr', 'Français'), ('de', 'Deutsch')], default='es', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='company_location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
