# Generated by Django 5.1 on 2024-08-18 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0015_company_company_language_company_company_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='compay_avatar',
            new_name='company_avatar',
        ),
    ]
