# Generated by Django 5.1 on 2024-10-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0016_rename_compay_avatar_company_company_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('pending', 'Pendiente de revisión'), ('published', 'Publicado')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='step_completed',
            field=models.IntegerField(default=0),
        ),
    ]
