# Generated by Django 5.1 on 2024-10-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_company_name_alter_freelancer_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='lastname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
